import { defineConfig } from "orval";

export default defineConfig({
  "todo-api": {
    output: {
      mode: "split",
      target: "./src/api/todo-api/api.ts",
      schemas: "./src/api/todo-api/models",
      client: "react-query",
      allParamsOptional: true,
      mock: false,
      override: {
        header: ({
          title,
          description,
          version,
        }: {
          title?: string;
          description?: string;
          version?: string;
        }) => [
          "Generated by orval 🍺",
          "Do not edit manually.",
          ...(title ? [title] : []),
          ...(description ? [description] : []),
          ...(version ? [`OpenAPI spec version: ${version}`] : []),
          "tslint:disable",
          "eslint-disable",
          "@ts-nocheck",
        ],
        mutator: {
          path: "./src/api/mutator/custom-instance.ts",
          name: "customInstance",
        },
      },
      headers: true,
    },
    input: {
      target: `http://localhost:4000/docs-json`,
    },
  },
});
