/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Todo API Documentation
 * API documentation generated from ts-rest contract
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */
import type { DeleteTodosId400ErrorsItem } from './deleteTodosId400ErrorsItem';

export type DeleteTodosId400 = {
  success: boolean;
  message: string;
  statusCode: number;
  errors?: DeleteTodosId400ErrorsItem[];
};
