/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Todo API Documentation
 * API documentation generated from ts-rest contract
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */
import type { GetTodos200DataItem } from './getTodos200DataItem';

export type GetTodos200 = {
  success: boolean;
  message: string;
  data: GetTodos200DataItem[];
  statusCode: number;
};
