/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Todo API Documentation
 * API documentation generated from ts-rest contract
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */
import type { GetTodosId400ErrorsItem } from './getTodosId400ErrorsItem';

export type GetTodosId400 = {
  success: boolean;
  message: string;
  statusCode: number;
  errors?: GetTodosId400ErrorsItem[];
};
