/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Todo API Documentation
 * API documentation generated from ts-rest contract
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */
import type { PostTodos201Data } from './postTodos201Data';

export type PostTodos201 = {
  success: boolean;
  message: string;
  data: PostTodos201Data;
  statusCode: number;
};
