/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Todo API Documentation
 * API documentation generated from ts-rest contract
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */
import type { PostAuthLogin200Data } from './postAuthLogin200Data';

export type PostAuthLogin200 = {
  success: boolean;
  message: string;
  data: PostAuthLogin200Data;
  statusCode: number;
};
