/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Todo API Documentation
 * API documentation generated from ts-rest contract
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */
import type { PostAuthRegister201Data } from './postAuthRegister201Data';

export type PostAuthRegister201 = {
  success: boolean;
  message: string;
  data: PostAuthRegister201Data;
  statusCode: number;
};
