/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Todo API Documentation
 * API documentation generated from ts-rest contract
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */

export type PostAuthLoginBody = {
  email: string;
  /**
   * @minLength 8
   * @maxLength 30
   */
  password: string;
};
