/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Todo API Documentation
 * API documentation generated from ts-rest contract
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */
import type { PostAuthRegister201DataUser } from './postAuthRegister201DataUser';

export type PostAuthRegister201Data = {
  token: string;
  user: PostAuthRegister201DataUser;
};
