/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Todo API Documentation
 * API documentation generated from ts-rest contract
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */
import type { PostAuthLogin200DataUser } from './postAuthLogin200DataUser';

export type PostAuthLogin200Data = {
  token: string;
  user: PostAuthLogin200DataUser;
};
