/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Todo API Documentation
 * API documentation generated from ts-rest contract
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */
import type { PutTodosId200Data } from './putTodosId200Data';

export type PutTodosId200 = {
  success: boolean;
  message: string;
  data: PutTodosId200Data;
  statusCode: number;
};
