/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Todo API Documentation
 * API documentation generated from ts-rest contract
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteTodosId200,
  DeleteTodosId400,
  DeleteTodosId401,
  DeleteTodosId403,
  DeleteTodosId404,
  DeleteTodosId409,
  DeleteTodosId500,
  GetAuthMe200,
  GetAuthMe400,
  GetAuthMe401,
  GetAuthMe403,
  GetAuthMe404,
  GetAuthMe409,
  GetAuthMe500,
  GetTodos200,
  GetTodos400,
  GetTodos401,
  GetTodos403,
  GetTodos404,
  GetTodos409,
  GetTodos500,
  GetTodosId200,
  GetTodosId400,
  GetTodosId401,
  GetTodosId403,
  GetTodosId404,
  GetTodosId409,
  GetTodosId500,
  PostAuthLogin200,
  PostAuthLogin400,
  PostAuthLogin401,
  PostAuthLogin403,
  PostAuthLogin404,
  PostAuthLogin409,
  PostAuthLogin500,
  PostAuthLoginBody,
  PostAuthRegister201,
  PostAuthRegister400,
  PostAuthRegister401,
  PostAuthRegister403,
  PostAuthRegister404,
  PostAuthRegister409,
  PostAuthRegister500,
  PostAuthRegisterBody,
  PostTodos201,
  PostTodos400,
  PostTodos401,
  PostTodos403,
  PostTodos404,
  PostTodos409,
  PostTodos500,
  PostTodosBody,
  PutTodosId200,
  PutTodosId400,
  PutTodosId401,
  PutTodosId403,
  PutTodosId404,
  PutTodosId409,
  PutTodosId500,
  PutTodosIdBody
} from './models';

import { customInstance } from '../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Register a new user
 */
export const postAuthRegister = (
    postAuthRegisterBody: PostAuthRegisterBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PostAuthRegister201>(
      {url: `/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAuthRegisterBody, signal
    },
      options);
    }
  


export const getPostAuthRegisterMutationOptions = <TError = PostAuthRegister400 | PostAuthRegister401 | PostAuthRegister403 | PostAuthRegister404 | PostAuthRegister409 | PostAuthRegister500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: PostAuthRegisterBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: PostAuthRegisterBody}, TContext> => {

const mutationKey = ['postAuthRegister'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthRegister>>, {data: PostAuthRegisterBody}> = (props) => {
          const {data} = props ?? {};

          return  postAuthRegister(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthRegister>>>
    export type PostAuthRegisterMutationBody = PostAuthRegisterBody
    export type PostAuthRegisterMutationError = PostAuthRegister400 | PostAuthRegister401 | PostAuthRegister403 | PostAuthRegister404 | PostAuthRegister409 | PostAuthRegister500

    /**
 * @summary Register a new user
 */
export const usePostAuthRegister = <TError = PostAuthRegister400 | PostAuthRegister401 | PostAuthRegister403 | PostAuthRegister404 | PostAuthRegister409 | PostAuthRegister500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: PostAuthRegisterBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthRegister>>,
        TError,
        {data: PostAuthRegisterBody},
        TContext
      > => {

      const mutationOptions = getPostAuthRegisterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Login with username and password
 */
export const postAuthLogin = (
    postAuthLoginBody: PostAuthLoginBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PostAuthLogin200>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAuthLoginBody, signal
    },
      options);
    }
  


export const getPostAuthLoginMutationOptions = <TError = PostAuthLogin400 | PostAuthLogin401 | PostAuthLogin403 | PostAuthLogin404 | PostAuthLogin409 | PostAuthLogin500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: PostAuthLoginBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: PostAuthLoginBody}, TContext> => {

const mutationKey = ['postAuthLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogin>>, {data: PostAuthLoginBody}> = (props) => {
          const {data} = props ?? {};

          return  postAuthLogin(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogin>>>
    export type PostAuthLoginMutationBody = PostAuthLoginBody
    export type PostAuthLoginMutationError = PostAuthLogin400 | PostAuthLogin401 | PostAuthLogin403 | PostAuthLogin404 | PostAuthLogin409 | PostAuthLogin500

    /**
 * @summary Login with username and password
 */
export const usePostAuthLogin = <TError = PostAuthLogin400 | PostAuthLogin401 | PostAuthLogin403 | PostAuthLogin404 | PostAuthLogin409 | PostAuthLogin500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: PostAuthLoginBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLogin>>,
        TError,
        {data: PostAuthLoginBody},
        TContext
      > => {

      const mutationOptions = getPostAuthLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Get current authenticated user information
 */
export const getAuthMe = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetAuthMe200>(
      {url: `/auth/me`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAuthMeQueryKey = () => {
    return [
    `/auth/me`
    ] as const;
    }

    
export const getGetAuthMeQueryOptions = <TData = Awaited<ReturnType<typeof getAuthMe>>, TError = GetAuthMe400 | GetAuthMe401 | GetAuthMe403 | GetAuthMe404 | GetAuthMe409 | GetAuthMe500>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthMe>>> = ({ signal }) => getAuthMe(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthMe>>>
export type GetAuthMeQueryError = GetAuthMe400 | GetAuthMe401 | GetAuthMe403 | GetAuthMe404 | GetAuthMe409 | GetAuthMe500


export function useGetAuthMe<TData = Awaited<ReturnType<typeof getAuthMe>>, TError = GetAuthMe400 | GetAuthMe401 | GetAuthMe403 | GetAuthMe404 | GetAuthMe409 | GetAuthMe500>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getAuthMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthMe<TData = Awaited<ReturnType<typeof getAuthMe>>, TError = GetAuthMe400 | GetAuthMe401 | GetAuthMe403 | GetAuthMe404 | GetAuthMe409 | GetAuthMe500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getAuthMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthMe<TData = Awaited<ReturnType<typeof getAuthMe>>, TError = GetAuthMe400 | GetAuthMe401 | GetAuthMe403 | GetAuthMe404 | GetAuthMe409 | GetAuthMe500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get current authenticated user information
 */

export function useGetAuthMe<TData = Awaited<ReturnType<typeof getAuthMe>>, TError = GetAuthMe400 | GetAuthMe401 | GetAuthMe403 | GetAuthMe404 | GetAuthMe409 | GetAuthMe500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAuthMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create a new todo
 */
export const postTodos = (
    postTodosBody: PostTodosBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PostTodos201>(
      {url: `/todos`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postTodosBody, signal
    },
      options);
    }
  


export const getPostTodosMutationOptions = <TError = PostTodos400 | PostTodos401 | PostTodos403 | PostTodos404 | PostTodos409 | PostTodos500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postTodos>>, TError,{data: PostTodosBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postTodos>>, TError,{data: PostTodosBody}, TContext> => {

const mutationKey = ['postTodos'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postTodos>>, {data: PostTodosBody}> = (props) => {
          const {data} = props ?? {};

          return  postTodos(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostTodosMutationResult = NonNullable<Awaited<ReturnType<typeof postTodos>>>
    export type PostTodosMutationBody = PostTodosBody
    export type PostTodosMutationError = PostTodos400 | PostTodos401 | PostTodos403 | PostTodos404 | PostTodos409 | PostTodos500

    /**
 * @summary Create a new todo
 */
export const usePostTodos = <TError = PostTodos400 | PostTodos401 | PostTodos403 | PostTodos404 | PostTodos409 | PostTodos500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postTodos>>, TError,{data: PostTodosBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postTodos>>,
        TError,
        {data: PostTodosBody},
        TContext
      > => {

      const mutationOptions = getPostTodosMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Get all todos
 */
export const getTodos = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetTodos200>(
      {url: `/todos`, method: 'GET', signal
    },
      options);
    }
  



export const getGetTodosQueryKey = () => {
    return [
    `/todos`
    ] as const;
    }

    
export const getGetTodosQueryOptions = <TData = Awaited<ReturnType<typeof getTodos>>, TError = GetTodos400 | GetTodos401 | GetTodos403 | GetTodos404 | GetTodos409 | GetTodos500>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTodosQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTodos>>> = ({ signal }) => getTodos(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTodosQueryResult = NonNullable<Awaited<ReturnType<typeof getTodos>>>
export type GetTodosQueryError = GetTodos400 | GetTodos401 | GetTodos403 | GetTodos404 | GetTodos409 | GetTodos500


export function useGetTodos<TData = Awaited<ReturnType<typeof getTodos>>, TError = GetTodos400 | GetTodos401 | GetTodos403 | GetTodos404 | GetTodos409 | GetTodos500>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodos>>,
          TError,
          Awaited<ReturnType<typeof getTodos>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTodos<TData = Awaited<ReturnType<typeof getTodos>>, TError = GetTodos400 | GetTodos401 | GetTodos403 | GetTodos404 | GetTodos409 | GetTodos500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodos>>,
          TError,
          Awaited<ReturnType<typeof getTodos>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTodos<TData = Awaited<ReturnType<typeof getTodos>>, TError = GetTodos400 | GetTodos401 | GetTodos403 | GetTodos404 | GetTodos409 | GetTodos500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all todos
 */

export function useGetTodos<TData = Awaited<ReturnType<typeof getTodos>>, TError = GetTodos400 | GetTodos401 | GetTodos403 | GetTodos404 | GetTodos409 | GetTodos500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTodosQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get a todo by id
 */
export const getTodosId = (
    id: string | undefined | null,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetTodosId200>(
      {url: `/todos/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetTodosIdQueryKey = (id?: string | undefined | null,) => {
    return [
    `/todos/${id}`
    ] as const;
    }

    
export const getGetTodosIdQueryOptions = <TData = Awaited<ReturnType<typeof getTodosId>>, TError = GetTodosId400 | GetTodosId401 | GetTodosId403 | GetTodosId404 | GetTodosId409 | GetTodosId500>(id: string | undefined | null, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodosId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTodosIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTodosId>>> = ({ signal }) => getTodosId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTodosId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTodosIdQueryResult = NonNullable<Awaited<ReturnType<typeof getTodosId>>>
export type GetTodosIdQueryError = GetTodosId400 | GetTodosId401 | GetTodosId403 | GetTodosId404 | GetTodosId409 | GetTodosId500


export function useGetTodosId<TData = Awaited<ReturnType<typeof getTodosId>>, TError = GetTodosId400 | GetTodosId401 | GetTodosId403 | GetTodosId404 | GetTodosId409 | GetTodosId500>(
 id: string | undefined | null, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodosId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodosId>>,
          TError,
          Awaited<ReturnType<typeof getTodosId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTodosId<TData = Awaited<ReturnType<typeof getTodosId>>, TError = GetTodosId400 | GetTodosId401 | GetTodosId403 | GetTodosId404 | GetTodosId409 | GetTodosId500>(
 id: string | undefined | null, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodosId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodosId>>,
          TError,
          Awaited<ReturnType<typeof getTodosId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTodosId<TData = Awaited<ReturnType<typeof getTodosId>>, TError = GetTodosId400 | GetTodosId401 | GetTodosId403 | GetTodosId404 | GetTodosId409 | GetTodosId500>(
 id: string | undefined | null, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodosId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a todo by id
 */

export function useGetTodosId<TData = Awaited<ReturnType<typeof getTodosId>>, TError = GetTodosId400 | GetTodosId401 | GetTodosId403 | GetTodosId404 | GetTodosId409 | GetTodosId500>(
 id: string | undefined | null, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodosId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTodosIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update a todo by id
 */
export const putTodosId = (
    id: string | undefined | null,
    putTodosIdBody: PutTodosIdBody,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<PutTodosId200>(
      {url: `/todos/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putTodosIdBody
    },
      options);
    }
  


export const getPutTodosIdMutationOptions = <TError = PutTodosId400 | PutTodosId401 | PutTodosId403 | PutTodosId404 | PutTodosId409 | PutTodosId500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putTodosId>>, TError,{id: string | undefined | null;data: PutTodosIdBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putTodosId>>, TError,{id: string | undefined | null;data: PutTodosIdBody}, TContext> => {

const mutationKey = ['putTodosId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putTodosId>>, {id: string | undefined | null;data: PutTodosIdBody}> = (props) => {
          const {id,data} = props ?? {};

          return  putTodosId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutTodosIdMutationResult = NonNullable<Awaited<ReturnType<typeof putTodosId>>>
    export type PutTodosIdMutationBody = PutTodosIdBody
    export type PutTodosIdMutationError = PutTodosId400 | PutTodosId401 | PutTodosId403 | PutTodosId404 | PutTodosId409 | PutTodosId500

    /**
 * @summary Update a todo by id
 */
export const usePutTodosId = <TError = PutTodosId400 | PutTodosId401 | PutTodosId403 | PutTodosId404 | PutTodosId409 | PutTodosId500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putTodosId>>, TError,{id: string | undefined | null;data: PutTodosIdBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putTodosId>>,
        TError,
        {id: string | undefined | null;data: PutTodosIdBody},
        TContext
      > => {

      const mutationOptions = getPutTodosIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Delete a todo by id
 */
export const deleteTodosId = (
    id: string | undefined | null,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<DeleteTodosId200>(
      {url: `/todos/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteTodosIdMutationOptions = <TError = DeleteTodosId400 | DeleteTodosId401 | DeleteTodosId403 | DeleteTodosId404 | DeleteTodosId409 | DeleteTodosId500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTodosId>>, TError,{id: string | undefined | null}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteTodosId>>, TError,{id: string | undefined | null}, TContext> => {

const mutationKey = ['deleteTodosId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTodosId>>, {id: string | undefined | null}> = (props) => {
          const {id} = props ?? {};

          return  deleteTodosId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteTodosIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTodosId>>>
    
    export type DeleteTodosIdMutationError = DeleteTodosId400 | DeleteTodosId401 | DeleteTodosId403 | DeleteTodosId404 | DeleteTodosId409 | DeleteTodosId500

    /**
 * @summary Delete a todo by id
 */
export const useDeleteTodosId = <TError = DeleteTodosId400 | DeleteTodosId401 | DeleteTodosId403 | DeleteTodosId404 | DeleteTodosId409 | DeleteTodosId500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTodosId>>, TError,{id: string | undefined | null}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTodosId>>,
        TError,
        {id: string | undefined | null},
        TContext
      > => {

      const mutationOptions = getDeleteTodosIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
